# Generated by Django 3.1.1 on 2021-01-22 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allroducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='pics')),
                ('Desc', models.TextField()),
                ('Price', models.IntegerField()),
                ('Container', models.CharField(max_length=200)),
                ('Box', models.IntegerField()),
                ('Percentage', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='orders_storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='productdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_data', models.JSONField()),
                ('Image', models.ImageField(upload_to='product_image')),
            ],
        ),
        migrations.CreateModel(
            name='robot_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items', models.IntegerField()),
                ('Products', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('order_complete', models.IntegerField()),
                ('order_pending', models.IntegerField()),
                ('order_processing', models.IntegerField()),
                ('Sells_amount', models.IntegerField()),
                ('containter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='productupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_data', models.JSONField()),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigRo.productdata')),
            ],
        ),
    ]
